version: 1.2
workflows:
 - name: Zip_Column_Content
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_zip_column.wdl
   testParameterFiles:
    - empty.json
 - name: Concatenate_Column_Content
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_cat_column.wdl
   testParameterFiles:
    - empty.json
